"""V17.7 — Dual Forward Paper Research (prospective, no real money)."""

from pathlib import Path

PAPER_ROOT = Path(__file__).resolve().parent
DATA_DIR = PAPER_ROOT / "data"
STATE_DIR = PAPER_ROOT / "state"
STATE_FILE = STATE_DIR / "paper_state.json"

AUDIT_VERSION = "v17_7"
APPROVED_FOR_REAL_MONEY = False
INITIAL_CAPITAL = 10_000.0
CASH_ASSET = "SHY"
MARKET_BENCHMARK = "SPY"
TRANSACTION_COST = 0.001
SLIPPAGE = 0.001
COST_RATE = TRANSACTION_COST + SLIPPAGE

R2_ON = 1.0
R2_OFF = 0.35
R2_SMA_WINDOW = 200
R2_SMA_SHIFT = 1

STRATEGY_R0 = "R0_BASE_S5"
STRATEGY_R2 = "R2_SPY_TREND"
STRATEGY_B1 = "B1_EQUAL_WEIGHT_CURRENT_ASOF"
STRATEGY_SPY = "SPY"

TRACKED_STRATEGIES = [STRATEGY_R0, STRATEGY_R2, STRATEGY_B1, STRATEGY_SPY]

REQUIRED_CLOSURE_STATUS = "V17_6_CLOSED_VALIDATED"
REQUIRED_OFFICIAL_OVERLAY = "NONE"
REQUIRED_CHALLENGER = "R2_SPY_TREND"
PAPER_TRADING_START = "2026-07-10"
